grpc:
  port: 4618
  maxInboundMessageSizeInKB: 16384
insightFinder:
  serverUrl: https://stg.insightfinder.com
  serverUri: /api/v1/customprojectrawdata
  checkAndCreateUri: /api/v1/check-and-add-custom-project
  promptUri: /api/v1/customprojectrawdata
  promptProjectName: ""
  promptSystemName: ""
  connectTimeout: 10
  readTimeout: 15
  writeTimeout: 15
jaeger:
  serverName: 172.31.56.88
  tlsEnabled: false
  grpcPort: 4317
  uiPort: 16686
  connectTimeout: 10
  readTimeout: 15
  writeTimeout: 15
app:
  traceWorkerNum: 8
  traceDelayInMillis: 10000
  enableTraceLog: false
  enablePromptLog: false
  tls:
    enabled: false
    certificateFile: ""
    privateKeyFile: ""
data:
  overwriteTraceAndSpanIdByUUID: true
  overwriteUUIDPath: "tags.chat.id"
  overwriteTimestamp: true
  overwriteTimestampPath: "tags.x-timestamp"
  useCustomTokenizer: true
  attrMapping:
    prompt_response:
      fieldPaths:
        - "tags.iftracer.entity.output"      # changed from tags.gen_ai.completion.0.content
    prompt_token:
      fieldPaths:
        - "tags.gen_ai.usage.input_tokens"
    response_token:
      fieldPaths:
        - "tags.gen_ai.usage.output_tokens"
    error:
      fieldPaths:
        - "tags.error_messages"
    username:
      fieldPaths:
        - "tags.chat.username"
        - "tags.username"
    session_id:
      fieldPaths:
        - "tags.uuid"
  promptExtraction:
    processPath: "tags.iftracer.entity.name"
    processNames:
      - "generate_answer"
    promptConfig:
      input_prompt:
        fieldPath: "tags.gen_ai.prompt.0.content"
        valuePath: ""
      output_prompt:
        fieldPath: "tags.iftracer.entity.output"   # changed from tags.gen_ai.completion.0.content
        valuePath: ""
  unsuccessResponseExtraction:
    processPath: "tags.iftracer.entity.name"
    processNames:
      - "generate_answer"
      - "generate_answer_with_context"
    config:
      output_prompt:
        fieldPath: "iftracer.entity.output"
sensitiveData:
  sensitiveDataFilterEnabled: false
  sensitiveDataRegex:
    - 'SELECT'
  replacement: ""